setwd("C:/Users/User/Downloads")
top50 <- read.csv("C:/Users/User/Downloads/top50.csv")
head(top50)
boxplot(top50$Valence.,main="Box-whisker Plot of Valence",border="black",col="light blue")
boxplot(top50$Valence.~top50$Artist.Name)
boxplot(top50$Valence.~top50$Artist.Name,ylab ='Valence',xlab ='Artist Name',main ='Valence of Artist Name in Top 50 of Spotify',xlim=c(2,47),col=c('lavender','plum'))
boxplot(top50$Valence.~top50$Genre,ylab ='Valence',xlab ='Genre',main ='Valence of Genre Songs in Top 50 Songs of Spotify',xlim =c(4,15),col=c('blueviolet','goldenrod','orange','seagreen','violet','coral'))
boxplot(top50$Popularity,main="Box-whisker plot of Popularity",border="brown",col="orange")
boxplot(top50$Popularity~top50$Artist.Name)
boxplot(top50$Popularity~top50$Artist.Name, ylab ='Popularity',xlab ='Artist Name',main ='Popularity of Artist Name in Top 50 of Spotify',ylim =c(80,95),xlim =c(4,12), border ='brown',col =c('orange','light blue'))
boxplot(top50$Acousticness..~top50$Artist.Name,ylab ='Acousticness',xlab ='Artist Name',main ='Acousticness Songs of Artist Name in Top 50 Songs of Spotify', xlim=c(2,5), col=c('blueviolet','goldenrod','orange','seagreen','violet','coral'))
boxplot(top50$Popularity~top50$Genre,ylab ='Popularity',xlab ='Genre',main ='Popularity of Genre Songs in Top 50 Songs of Spotify',xlim =c(5,16),col=c('blueviolet','goldenrod','orange','seagreen','violet','coral'))
boxplot(top50$Liveness,main="Box-whisker Plot of Liveness",border="black",col="grey")
boxplot(top50$Liveness~top50$Artist.Name,ylab ='Liveness',xlab ='Artist Name',main ='Liveness Songs of Artist in Top 50 Songs of Spotify',xlim=c(2,12),col=c('blueviolet','goldenrod','plum','seagreen','navyblue','coral'))
boxplot(top50$Liveness~top50$Genre,ylab ='Liveness',xlab ='Genre',main ='Liveness Songs of Genre in Top 50 Songs of Spotify',xlim=c(4,18),col=c('blueviolet','goldenrod','plum','seagreen','navyblue','coral'))
boxplot(top50$Length.,main="Box-whisker Plot of Length",border="black",col="royal blue")
boxplot(top50$Length.~top50$Track.Name,ylab ='Length',xlab ='Artist Name',main ='Duration Songs of Track Name in Top 50 Songs of Spotify',col=c('blueviolet','goldenrod','orange','seagreen','violet','coral'))
boxplot(top50$Loudness..dB..,main="Box-whisker Plot of Loudness..dB..",border="black",col="red")
boxplot(top50$Loudness..dB..~top50$Artist.Name, ylab ='Loudness',xlab ='Artist Name',main ='Loudness of Track Name in Top 50 Song of Spotify',xlim=c(9,12))
boxplot(top50$Speechiness.,main="Box-whisker Plot of Speechiness",border="black",col="light pink")
boxplot(top50$Speechiness.~top50$Artist.Name, ylab ='Speechiness',xlab ='Artist Name',main ='Speechiness of Artist Name in Top 50 Song of Spotify',xlim=c(2,6))
boxplot(top50$Danceability,main="Box-whisker Plot of Danceability",border="black",col="pink")
boxplot(top50$Danceability~top50$Genre,ylab ='Danceability',xlab ='Genre',main ='Danceability Songs of Genre in Top 50 Songs of Spotify',xlim=c(9,12),col=c('blueviolet','goldenrod','plum','seagreen','skyblue','coral'))
boxplot(top50$Danceability~top50$Artist.Name,ylab ='Danceability',xlab ='Artist Name',main ='Danceability Songs of Artists in Top 50 Songs of Spotify',xlim=c(4,17),col=c('blueviolet','goldenrod','plum','seagreen','skyblue','coral'))
boxplot(top50$Acousticness..,main="Box-whisker Plot of Acousticness",border="black",col="purple")
boxplot(top50$Acoustiness~top50$Artist.Name,ylab ='Acousticness',xlab ='Artist Name',main ='Acousticness Songs of Artist Name in Top 50 Songs of Spotify',col=c('blueviolet','goldenrod','orange','seagreen','violet','coral'))
boxplot(top50$Acoustiness~top50$Genre,ylab ='Acousticness',xlab ='Genre',main ='Acousticness Songs of genre in Top 50 Songs of Spotify', xlim =c(3,20),col=c('blueviolet','goldenrod','orange','seagreen','violet','coral'))
Artist.Name=c(1,26)
Genre=c(1,26)
Valence=c(1,26)
Popularity=c(1,26)
boxplot(Artist.Name,Genre,Valence,Popularity,names =c('Artist Name','Genre','Valence','Popularity'),main ='Shawn Mendes of Songs in Top 50 Songs of Spotify',col =c('purple','turquoise','darkgrey','maroon'))
Artist.Name=c(4,6,38,50)
Genre=c(4,6,38,50)
Valence=c(4,8,38,50)
Popularity=c(4,8,38,50)
boxplot(Artist.Name,Genre,Valence,Popularity, names=c('Artist Name','Genre','Valence','Popularity'),main = 'Songs of Ed Sheeran's in Top 50 Song of Spotify',col=c('navyblue','darkgreen','violet','gold'))
boxplot(top50$Energy,main="Box-whisker plot of Energy",border="black",col="green")
boxplot(top50$Energy,main="Box-whisker plot of Energy",border="black",col="green")
boxplot(top50$Beats.Per.Minute,main="Box-whisker plot of Beats Per Minute",border="black",col="blue")

